# Kubernetes Deployment to manage NGINX pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  # Number of identical pods to maintain
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      # Container configuration for NGINX
      - name: nginx
        image: nginx:1.21.3
        ports:
        - containerPort: 80  # Port where NGINX will listen